name: Continuous Integration 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  #---------------------docker-image ----------------------
  docker-image-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  #-------------------php------------------------
  php-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2


    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
  #-----------------------Symfony---------------------
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: 'PHP 7.4.9'
    - uses: actions/checkout@v2
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Create Database
      run: |
        mkdir -p data
        touch data/database
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DATABASE_URL: mysql://db_user:db_password@127.0.0.1:3306/db_name?serverVersion=5.7
      run: vendor/bin/phpunit


